version: "3.9"

services:
    nginx:
        image: nginx
        build: requirements/nginx/
        container_name: nginx
        restart: always
        env_file: .env
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html/
        networks:
            - inception
        depends_on:
            - wordpress
    wordpress:
        image: wordpress
        build: requirements/wordpress/
        container_name: wordpress
        restart: always
        env_file: .env
        volumes:
            - wordpress:/var/www/html/
        networks:
            - inception
        depends_on:
            - mariadb
    mariadb:
        image: mariadb
        build: requirements/mariadb/
        container_name: mariadb
        restart: always
        env_file: .env
        volumes:
            - mariadb:/var/lib/mysql/
        networks:
            - inception

volumes:
    wordpress:
        name: wordpress
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/data/wordpress/
    mariadb:
        name: mariadb
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ~/data/mariadb/

networks:
    inception:
        name: inception
        driver: bridge
